### PR TITLE
Fixing some deprecation notices

### PR DESCRIPTION
**Pull request by jjasghar**
`default` is being replaced by `value`

### CODE REVIEW

**Comment by artem-sidorenko** [comment]
@jjasghar thanks for this PR! Is this change backward compatible to inspec 3? We have to maintain support of inspec 3 for a while.

**Comment by chris-rock** [comment]
@artem-sidorenko I just double-checked it yesterday for dev-sec/linux-baseline/pull/119 The use of value is fine as long as we update the minimum InSpec version to 3.4.1 in the readme (see https://github.com/inspec/inspec/blob/95ed2696e98181133cc586797d90e1ff777f79a4/CHANGELOG.md#v341-2019-01-29)

**Comment by artem-sidorenko** [comment]
@chris-rock thanks!

**Comment by artem-sidorenko** [comment]
@chris-rock we do not have any inspec version in the README here, should we just merge this PR?

**Comment by chris-rock** [comment]
Yes, we can. I think we should mention somewhere that we aim to stay InSpec 3 compatible.

**Pull request merged**
