### PR TITLE
CIS 4.1.1.3

### PR DESCRIPTION
**Pull request by tomhaynes**
For CIS v2.1:

4.1.1.3 Ensure audit logs are not automatically deleted:

Audit:
Run the following command and verify output matches:
```max_log_file_action = keep_logs```

### CODE REVIEW

**Comment by artem-sidorenko** [comment]
@chris-rock @atomic111 this change has [broken](https://travis-ci.org/artem-forks/chef-os-hardening/jobs/304789723) the tests for chef-os-hardening. As we currently are not managing the audit configuration, any ideas how to handle this?  (I do not have time to implement it now) Should we create an issue in the implementation repo and disable this test for now?

**Comment by artem-sidorenko** [comment]
I created https://github.com/dev-sec/chef-os-hardening/issues/182 and https://github.com/dev-sec/chef-os-hardening/issues/181

**Comment by chris-rock** [comment]
We could pin to released versions of the benchmark...

**Comment by artem-sidorenko** [comment]
@chris-rock Hm, okay. But this would lead to a recurrent version repining, right?

**Comment by chris-rock** [comment]
yes, unfortunately. I am open to any other idea

**Comment by artem-sidorenko** [comment]
@chris-rock I do not have any other idea :\ For me personally its easier to live with a current setup (#55 would make it even better). But if somebody has a better idea, I would be also happy to hear it

**Pull request merged**
